databases:
  - name: mercado-db
    plan: free
    region: oregon
    databaseName: mercado_db
    user: mercado_user

services:
  - type: web
    name: mercado-local
    runtime: docker
    plan: starter
    region: oregon
    numInstances: 1
    healthCheckPath: /
    disk:
      name: mercado_uploads
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: "Mercado Palosante√±o"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: mercado-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr