databases:
  - name: mercado-db
    plan: free            # Entramos gratis para evitar errores de validación.
    region: oregon
    databaseName: mercado_db
    user: mercado_user

services:
  - type: web
    name: mercado-local
    runtime: docker
    plan: starter         # El web service sí lo dejamos pago ($7) desde el inicio.
    region: oregon
    numInstances: 1
    healthCheckPath: /
    disk:
      name: mercado_uploads
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: "Mercado Palosanteño"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generate: true    # <--- AQUÍ ESTABA EL ERROR (Corregido)
      - key: DATABASE_URL
        fromDatabase:
          name: mercado-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr