services:
  - type: web
    name: mercado-local
    env: docker
    plan: starter
    disk:
      name: mercado_uploads
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: mercado-local-db
          property: connectionString

databases:
  - name: mercado-local-db
    plan: starter
    databaseName: mercado_local
    user: mercado_user
