services:
  # 1. El Servidor Web (Tu Laravel)
  - type: web
    name: mercado-local
    runtime: docker
    plan: starter      # Para el servicio web, 'starter' SÍ sigue funcionando.
    region: oregon
    numInstances: 1
    healthCheckPath: /
    disk:
      name: mercado_uploads
      mountPath: /var/www/html/storage/app/public
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: "Mercado Palosanteño"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generate: true
      - key: DATABASE_URL
        fromDatabase:
          name: mercado-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr

  # 2. La Base de Datos (Postgres)
  - type: psql
    name: mercado-db
    plan: basic        # <--- ESTE FUE EL CAMBIO (Antes era 'starter')
    region: oregon
    databaseName: mercado_db
    user: mercado_user

databases:
  - name: mercado-db
    plan: basic        # <--- AQUÍ TAMBIÉN CAMBIALO
