services:
  - type: web
    name: mercado-local
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan migrate --force
    startCommand: heroku-php-nginx public/
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: mercado-local-db
          property: connectionString

databases:
  - name: mercado-local-db
    plan: free
    databaseName: mercado_local
    user: mercado_user
